<a href="https://colab.research.google.com/github/BuiGiaAn/ThucHanhToanCC/blob/main/Chuong5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Thực hành 1: Lặp để tìm nghiệm 

In [1]:
x = 3
print  (x) 

3


In [3]:
import math
x = math.sqrt(1+x)
print (x) 

2.0


In [4]:
 x = math.sqrt(1+x)
 print (x) 

1.7320508075688772


In [5]:
 x = math.sqrt(1+x)
 print (x) 

1.6528916502810695


# **Thực hành 2: Lặp bằng while để tìm nghiệm**

In [6]:
import math
x = 3
lap = 1
while (x != math.sqrt(x+1)): 
  x = math.sqrt(x+1) 
  lap = lap  +1     

In [8]:
x

1.618033988749895

In [7]:
lap

32

# **Thực hành 3: Giải phương trình bằng hàm solve trong sympy**

In [10]:
import sympy as sp
from sympy import Symbol
x = Symbol('x')
sp.solve(x-sp.sqrt(1+x),x)

[1/2 + sqrt(5)/2]

# **Thực hành 4: Các phép toán trên vector **

In [13]:
import numpy as np
v1 = np.array([1., 2., 3.])
v2 = np.array([2., 1., 0.])
v3 = v1 + v2
v3 


IndentationError: ignored

In [14]:
3*v1  + 2*v2 

array([7., 8., 9.])

In [16]:
[1, 2, 3] + [2, 1, 0] 

[1, 2, 3, 2, 1, 0]

In [15]:
[1, 2, 3] + [2, 1, 0] 

[1, 2, 3, 2, 1, 0]

In [18]:
v4 = np.hstack([v1, v2]) 

In [19]:
np.dot(v1, v2)

4.0

In [20]:
angles = np.linspace(0, np.pi/2, 5)
angles

array([0.        , 0.39269908, 0.78539816, 1.17809725, 1.57079633])

In [ ]:
np.sin(angles) 

In [26]:
'''import sympy as sy
sy.sin(angles)''' 
from sympy import sin as sysin
angles = np.linspace(0, np.pi/2, 5)
sinangle = np.zeros(5)
len(angles)
for i in range(len(angles)):
   sinangle[i] = sysin(angles[i])  
sinangle 


array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

# **Thực hành 5:**

In [27]:
import numpy as np
goc = np.pi/3
A = np.array([ [np.cos(goc), -np.sin(goc)],[np.sin(goc),  np.cos(goc)] ]) 
V = np.array([1. , 0. ])
Y = np.dot(A, V)
Y 

array([0.5      , 0.8660254])

# **Thực hành 6:**

In [30]:
from numpy import diff
dx = 0.1
y = [1, 2, 3, 4, 4, 5, 6] 
dy = diff(y)/dx
dy 

array([10., 10., 10.,  0., 10., 10.])

In [31]:
z = np.array([1, 2, 3, 4, 4, 5, 6])
dz = diff(z)/dx
dz 

array([10., 10., 10.,  0., 10., 10.])

In [32]:
from numpy import diff
x = [.1, .2, .5, .6, .7, .8, .9]
y = [1, 2, 3, 4, 4, 5, 6]
dydx = diff(y)/diff(x)
print (dydx) 

[10.          3.33333333 10.          0.         10.         10.        ]


# **Thực hành 7:**

**Tạo các điểm P1, P2, P3 và P4 **

In [34]:
from sympy.geometry import * 
P1 = Point(0, 0)
P2 = Point(3, 4)
P3 = Point(2, -1)
P4 = Point(-1, 5) 

**Tạo 2 đoạn đường S1 và S2: **

In [35]:
S1 = Segment(P1, P2)
S2 = Segment(P3, P4) 

**Kiểm 3 điểm thẳng hàng: **

In [36]:
Point.is_collinear(P1, P2, P3) 

False

**Độ dài của đoạn đường S1**

In [38]:
S1.length

5

Lấy trung điểm của đoạn 2: 

In [39]:
S2.midpoint

Point2D(1/2, 2)

Tính độ dốc của đường S1 

In [40]:
S1.slope 

4/3

Tìm vị trí giao nhau giữa hai đoạn đường 

In [41]:
S1.intersection(S2)

[Point2D(9/10, 6/5)]

Góc giữa hai đoạn đường 

In [42]:
Segment.angle_between(S1, S2) 

acos(sqrt(5)/5)

Kiểm đoạn đường S1 có chứa điểm P3 hay không?

In [ ]:
S1.contains(P3) 

Lập và xem phương trình đường thẳng L1 đi qua 2 điểm P1 và P2:

In [43]:
L1 = Line(P1, P2)
L1.equation()  

-4*x + 3*y

Kiểm tính song song: 

In [44]:
 L1.is_parallel(S1) 

True

In [45]:
 L1.is_parallel(S2) 

False