<a href="https://colab.research.google.com/github/BuiGiaAn/ThucHanhToanCC/blob/main/Chuong5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Thực hành 1: Lặp để tìm nghiệm 

In [1]:
x = 3
print  (x) 

3


In [3]:
import math
x = math.sqrt(1+x)
print (x) 

2.0


In [4]:
 x = math.sqrt(1+x)
 print (x) 

1.7320508075688772


In [5]:
 x = math.sqrt(1+x)
 print (x) 

1.6528916502810695


# **Thực hành 2: Lặp bằng while để tìm nghiệm**

In [6]:
import math
x = 3
lap = 1
while (x != math.sqrt(x+1)): 
  x = math.sqrt(x+1) 
  lap = lap  +1     

In [8]:
x

1.618033988749895

In [7]:
lap

32

# **Thực hành 3: Giải phương trình bằng hàm solve trong sympy**

In [10]:
import sympy as sp
from sympy import Symbol
x = Symbol('x')
sp.solve(x-sp.sqrt(1+x),x)

[1/2 + sqrt(5)/2]

# **Thực hành 4: Các phép toán trên vector **

In [13]:
import numpy as np
v1 = np.array([1., 2., 3.])
v2 = np.array([2., 1., 0.])
v3 = v1 + v2
v3 


IndentationError: ignored

In [14]:
3*v1  + 2*v2 

array([7., 8., 9.])

In [16]:
[1, 2, 3] + [2, 1, 0] 

[1, 2, 3, 2, 1, 0]

In [15]:
[1, 2, 3] + [2, 1, 0] 

[1, 2, 3, 2, 1, 0]

In [18]:
v4 = np.hstack([v1, v2]) 

In [19]:
np.dot(v1, v2)

4.0

In [20]:
angles = np.linspace(0, np.pi/2, 5)
angles

array([0.        , 0.39269908, 0.78539816, 1.17809725, 1.57079633])

In [ ]:
np.sin(angles) 

In [26]:
'''import sympy as sy
sy.sin(angles)''' 
from sympy import sin as sysin
angles = np.linspace(0, np.pi/2, 5)
sinangle = np.zeros(5)
len(angles)
for i in range(len(angles)):
   sinangle[i] = sysin(angles[i])  
sinangle 


array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

# **Thực hành 5:**

In [27]:
import numpy as np
goc = np.pi/3
A = np.array([ [np.cos(goc), -np.sin(goc)],[np.sin(goc),  np.cos(goc)] ]) 
V = np.array([1. , 0. ])
Y = np.dot(A, V)
Y 

array([0.5      , 0.8660254])

# **Thực hành 6:**

In [30]:
from numpy import diff
dx = 0.1
y = [1, 2, 3, 4, 4, 5, 6] 
dy = diff(y)/dx
dy 

array([10., 10., 10.,  0., 10., 10.])

In [31]:
z = np.array([1, 2, 3, 4, 4, 5, 6])
dz = diff(z)/dx
dz 

array([10., 10., 10.,  0., 10., 10.])